###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

####swagger相关配置
swagger:
  base-package: com.lz.member.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 该项目 自主使用
  version: 1.1
  contact:
    name: lz
    email: 373720781@qq.com
logging:
  level:
    com.lz.member.mapper: DEBUG
